# Generated by Django 6.0.6 on 2026-07-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], max_length=10, verbose_name='Приём пищи')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Приём пищи',
                'verbose_name_plural': 'Приёмы пищи',
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('is_liquid', models.BooleanField(default=False, verbose_name='Жидкость')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Масса (г/мл)')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Калорийность (на 100 г/мл)')),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Белки (на 100 г/мл)')),
                ('fat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Жиры (на 100 г/мл)')),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Углеводы (на 100 г/мл)')),
            ],
            options={
                'verbose_name': 'Съеденный продукт',
                'verbose_name_plural': 'Съеденные продукты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('is_liquid', models.BooleanField(default=False, verbose_name='Жидкость')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Калорийность (на 100 г/мл)')),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Белки (на 100 г/мл)')),
                ('fat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Жиры (на 100 г/мл)')),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Углеводы (на 100 г/мл)')),
            ],
            options={
                'verbose_name': 'Системный продукт питания',
                'verbose_name_plural': 'Системные продукты питания',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('is_liquid', models.BooleanField(default=False, verbose_name='Жидкость')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Калорийность (на 100 г/мл)')),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Белки (на 100 г/мл)')),
                ('fat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Жиры (на 100 г/мл)')),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Углеводы (на 100 г/мл)')),
            ],
            options={
                'verbose_name': 'Пользовательский продукт питания',
                'verbose_name_plural': 'Пользовательские продукты питания',
            },
        ),
    ]
