# Generated by Django 6.0.6 on 2026-07-08 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.meal', verbose_name='Приём пищи'),
        ),
    ]
