# Generated by Django 6.0.6 on 2026-08-16 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_mealitem_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Калорийность (на 100 г/мл)'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Углеводы (на 100 г/мл)'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Жиры (на 100 г/мл)'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Белки (на 100 г/мл)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Калорийность (на 100 г/мл)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Углеводы (на 100 г/мл)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Жиры (на 100 г/мл)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Белки (на 100 г/мл)'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Калорийность (на 100 г/мл)'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Углеводы (на 100 г/мл)'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Жиры (на 100 г/мл)'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Белки (на 100 г/мл)'),
        ),
    ]
