# Generated by Django 6.0.6 on 2026-09-08 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_alter_mealitem_calories_alter_mealitem_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Масса (всего, за указанное количество)'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Калорийность (всего, за указанное количество)'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Углеводы (всего, за указанное количество)'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Жиры (всего, за указанное количество)'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Белки (всего, за указанное количество)'),
        ),
    ]
